# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20 (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Create .env file
        run: |
          cat <<EOF > .env
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
          EOF

      - name: Debug .env contents
        run: |
          echo "Contents of .env:"
          sed -n '1p;2p' .env

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run connect.js
        run: node connect.js
