# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create .env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        
      - name: Test MongoDB connection
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: |
          if [ -n "$MONGODB_URI" ]; then
            node -r dotenv/config connect.js
          else
            echo "Skipping MongoDB connection test - MONGODB_URI not provided"
            exit 0
          fi
